version: 2
archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
builds:
- binary: pulumi-resource-sdm
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X github.com/pierskarsenbarg/pulumi-sdm/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-sdm/
changelog:
  disable: true
release:
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'