// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm
{
    /// <summary>
    /// ApprovalWorkflowApprover links an approval workflow approver to an ApprovalWorkflowStep
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sdm = PiersKarsenbarg.Sdm;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var approvalWorkflowApproverAccountExample = new Sdm.ApprovalWorkflowApprover("approvalWorkflowApproverAccountExample", new()
    ///     {
    ///         AccountId = "a-234605",
    ///         ApprovalFlowId = "af-6799234",
    ///         ApprovalStepId = "afs-2956266",
    ///     });
    /// 
    ///     var approvalWorkflowApproverRoleExample = new Sdm.ApprovalWorkflowApprover("approvalWorkflowApproverRoleExample", new()
    ///     {
    ///         ApprovalFlowId = "af-1935694",
    ///         ApprovalStepId = "afs-9245942",
    ///         RoleId = "r-542982",
    ///     });
    /// 
    /// });
    /// ```
    /// This resource can be imported using the import command.
    /// 
    /// ## Import
    /// 
    /// A ApprovalWorkflowApprover can be imported using the id, e.g.,
    /// 
    /// ```sh
    /// $ pulumi import sdm:index/approvalWorkflowApprover:ApprovalWorkflowApprover example afa-12345678
    /// ```
    /// </summary>
    [SdmResourceType("sdm:index/approvalWorkflowApprover:ApprovalWorkflowApprover")]
    public partial class ApprovalWorkflowApprover : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The approver account id.
        /// </summary>
        [Output("accountId")]
        public Output<string?> AccountId { get; private set; } = null!;

        /// <summary>
        /// The approval flow id specified the approval workflow that this approver belongs to
        /// </summary>
        [Output("approvalFlowId")]
        public Output<string> ApprovalFlowId { get; private set; } = null!;

        /// <summary>
        /// The approval step id specified the approval flow step that this approver belongs to
        /// </summary>
        [Output("approvalStepId")]
        public Output<string> ApprovalStepId { get; private set; } = null!;

        /// <summary>
        /// The approver role id
        /// </summary>
        [Output("roleId")]
        public Output<string?> RoleId { get; private set; } = null!;


        /// <summary>
        /// Create a ApprovalWorkflowApprover resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApprovalWorkflowApprover(string name, ApprovalWorkflowApproverArgs args, CustomResourceOptions? options = null)
            : base("sdm:index/approvalWorkflowApprover:ApprovalWorkflowApprover", name, args ?? new ApprovalWorkflowApproverArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApprovalWorkflowApprover(string name, Input<string> id, ApprovalWorkflowApproverState? state = null, CustomResourceOptions? options = null)
            : base("sdm:index/approvalWorkflowApprover:ApprovalWorkflowApprover", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pierskarsenbarg/pulumi-sdm",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApprovalWorkflowApprover resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApprovalWorkflowApprover Get(string name, Input<string> id, ApprovalWorkflowApproverState? state = null, CustomResourceOptions? options = null)
        {
            return new ApprovalWorkflowApprover(name, id, state, options);
        }
    }

    public sealed class ApprovalWorkflowApproverArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The approver account id.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// The approval flow id specified the approval workflow that this approver belongs to
        /// </summary>
        [Input("approvalFlowId", required: true)]
        public Input<string> ApprovalFlowId { get; set; } = null!;

        /// <summary>
        /// The approval step id specified the approval flow step that this approver belongs to
        /// </summary>
        [Input("approvalStepId", required: true)]
        public Input<string> ApprovalStepId { get; set; } = null!;

        /// <summary>
        /// The approver role id
        /// </summary>
        [Input("roleId")]
        public Input<string>? RoleId { get; set; }

        public ApprovalWorkflowApproverArgs()
        {
        }
        public static new ApprovalWorkflowApproverArgs Empty => new ApprovalWorkflowApproverArgs();
    }

    public sealed class ApprovalWorkflowApproverState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The approver account id.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// The approval flow id specified the approval workflow that this approver belongs to
        /// </summary>
        [Input("approvalFlowId")]
        public Input<string>? ApprovalFlowId { get; set; }

        /// <summary>
        /// The approval step id specified the approval flow step that this approver belongs to
        /// </summary>
        [Input("approvalStepId")]
        public Input<string>? ApprovalStepId { get; set; }

        /// <summary>
        /// The approver role id
        /// </summary>
        [Input("roleId")]
        public Input<string>? RoleId { get; set; }

        public ApprovalWorkflowApproverState()
        {
        }
        public static new ApprovalWorkflowApproverState Empty => new ApprovalWorkflowApproverState();
    }
}
