// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm
{
    public static class GetAccountGroup
    {
        /// <summary>
        /// An AccountGroup is a link between an Account and a Group.
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var securityLeadGroups = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         AccountId = securityLead.Id,
        ///     });
        /// 
        ///     var specificRelationship = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         Id = "accountgroup-1234567890abcdef",
        ///     });
        /// 
        ///     var usersInGroup = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         GroupId = devopsGroup.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetAccountGroupResult> InvokeAsync(GetAccountGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAccountGroupResult>("sdm:index/getAccountGroup:getAccountGroup", args ?? new GetAccountGroupArgs(), options.WithDefaults());

        /// <summary>
        /// An AccountGroup is a link between an Account and a Group.
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var securityLeadGroups = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         AccountId = securityLead.Id,
        ///     });
        /// 
        ///     var specificRelationship = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         Id = "accountgroup-1234567890abcdef",
        ///     });
        /// 
        ///     var usersInGroup = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         GroupId = devopsGroup.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetAccountGroupResult> Invoke(GetAccountGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountGroupResult>("sdm:index/getAccountGroup:getAccountGroup", args ?? new GetAccountGroupInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// An AccountGroup is a link between an Account and a Group.
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var securityLeadGroups = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         AccountId = securityLead.Id,
        ///     });
        /// 
        ///     var specificRelationship = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         Id = "accountgroup-1234567890abcdef",
        ///     });
        /// 
        ///     var usersInGroup = Sdm.GetAccountGroup.Invoke(new()
        ///     {
        ///         GroupId = devopsGroup.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetAccountGroupResult> Invoke(GetAccountGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountGroupResult>("sdm:index/getAccountGroup:getAccountGroup", args ?? new GetAccountGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAccountGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Unique identifier of the Account.
        /// </summary>
        [Input("accountId")]
        public string? AccountId { get; set; }

        /// <summary>
        /// Unique identifier of the Group.
        /// </summary>
        [Input("groupId")]
        public string? GroupId { get; set; }

        /// <summary>
        /// Unique identifier of the AccountGroup.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        public GetAccountGroupArgs()
        {
        }
        public static new GetAccountGroupArgs Empty => new GetAccountGroupArgs();
    }

    public sealed class GetAccountGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Unique identifier of the Account.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Unique identifier of the Group.
        /// </summary>
        [Input("groupId")]
        public Input<string>? GroupId { get; set; }

        /// <summary>
        /// Unique identifier of the AccountGroup.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        public GetAccountGroupInvokeArgs()
        {
        }
        public static new GetAccountGroupInvokeArgs Empty => new GetAccountGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetAccountGroupResult
    {
        /// <summary>
        /// Unique identifier of the Account.
        /// </summary>
        public readonly string? AccountId;
        /// <summary>
        /// A list where each element has the following attributes:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAccountGroupAccountsGroupResult> AccountsGroups;
        /// <summary>
        /// Unique identifier of the Group.
        /// </summary>
        public readonly string? GroupId;
        /// <summary>
        /// Unique identifier of the AccountGroup.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// a list of strings of ids of data sources that match the given arguments.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetAccountGroupResult(
            string? accountId,

            ImmutableArray<Outputs.GetAccountGroupAccountsGroupResult> accountsGroups,

            string? groupId,

            string? id,

            ImmutableArray<string> ids)
        {
            AccountId = accountId;
            AccountsGroups = accountsGroups;
            GroupId = groupId;
            Id = id;
            Ids = ids;
        }
    }
}
