// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm
{
    public static class GetAccount
    {
        /// <summary>
        /// Accounts are users that have access to strongDM. The types of accounts are:
        ///  1. **Users:** humans who are authenticated through username and password or SSO.
        ///  2. **Service Accounts:** machines that are authenticated using a service token.
        ///  3. **Tokens** are access keys with permissions that can be used for authentication.
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as sdm from "@pierskarsenbarg/sdm";
        /// 
        /// const user_queries = sdm.getAccount({
        ///     type: "user",
        ///     email: "*@strongdm.com",
        ///     tags: {
        ///         region: "us-west",
        ///         env: "dev",
        ///     },
        /// });
        /// const api_key_queries = sdm.getAccount({
        ///     type: "api",
        ///     name: "*-dev",
        /// });
        /// const admin_token_queries = sdm.getAccount({
        ///     type: "admin-token",
        ///     name: "*-prod",
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_sdm as sdm
        /// 
        /// user_queries = sdm.get_account(type="user",
        ///     email="*@strongdm.com",
        ///     tags={
        ///         "region": "us-west",
        ///         "env": "dev",
        ///     })
        /// api_key_queries = sdm.get_account(type="api",
        ///     name="*-dev")
        /// admin_token_queries = sdm.get_account(type="admin-token",
        ///     name="*-prod")
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = PiersKarsenbarg.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var user_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "user",
        ///         Email = "*@strongdm.com",
        ///         Tags = 
        ///         {
        ///             { "region", "us-west" },
        ///             { "env", "dev" },
        ///         },
        ///     });
        /// 
        ///     var api_key_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "api",
        ///         Name = "*-dev",
        ///     });
        /// 
        ///     var admin_token_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "admin-token",
        ///         Name = "*-prod",
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/pierskarsenbarg/pulumi-sdm/sdk/go/sdm"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type:  pulumi.StringRef("user"),
        /// 			Email: pulumi.StringRef("*@strongdm.com"),
        /// 			Tags: map[string]interface{}{
        /// 				"region": "us-west",
        /// 				"env":    "dev",
        /// 			},
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		_, err = sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type: pulumi.StringRef("api"),
        /// 			Name: pulumi.StringRef("*-dev"),
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		_, err = sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type: pulumi.StringRef("admin-token"),
        /// 			Name: pulumi.StringRef("*-prod"),
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     sdm = {
        ///       source = "pulumi/sdm"
        ///     }
        ///   }
        /// }
        /// 
        /// data "sdm_getaccount" "user-queries" {
        ///   type  = "user"
        ///   email = "*@strongdm.com"
        ///   tags = {
        ///     "region" = "us-west"
        ///     "env"    = "dev"
        ///   }
        /// }
        /// data "sdm_getaccount" "api-key-queries" {
        ///   type = "api"
        ///   name = "*-dev"
        /// }
        /// data "sdm_getaccount" "admin-token-queries" {
        ///   type = "admin-token"
        ///   name = "*-prod"
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.sdm.SdmFunctions;
        /// import com.pulumi.sdm.inputs.GetAccountArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var user-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("user")
        ///             .email("*@strongdm.com")
        ///             .tags(Map.ofEntries(
        ///                 Map.entry("region", "us-west"),
        ///                 Map.entry("env", "dev")
        ///             ))
        ///             .build());
        /// 
        ///         final var api-key-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("api")
        ///             .name("*-dev")
        ///             .build());
        /// 
        ///         final var admin-token-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("admin-token")
        ///             .name("*-prod")
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   user-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: user
        ///         email: '*@strongdm.com'
        ///         tags:
        ///           region: us-west
        ///           env: dev
        ///   api-key-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: api
        ///         name: '*-dev'
        ///   admin-token-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: admin-token
        ///         name: '*-prod'
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Task<GetAccountResult> InvokeAsync(GetAccountArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAccountResult>("sdm:index/getAccount:getAccount", args ?? new GetAccountArgs(), options.WithDefaults());

        /// <summary>
        /// Accounts are users that have access to strongDM. The types of accounts are:
        ///  1. **Users:** humans who are authenticated through username and password or SSO.
        ///  2. **Service Accounts:** machines that are authenticated using a service token.
        ///  3. **Tokens** are access keys with permissions that can be used for authentication.
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as sdm from "@pierskarsenbarg/sdm";
        /// 
        /// const user_queries = sdm.getAccount({
        ///     type: "user",
        ///     email: "*@strongdm.com",
        ///     tags: {
        ///         region: "us-west",
        ///         env: "dev",
        ///     },
        /// });
        /// const api_key_queries = sdm.getAccount({
        ///     type: "api",
        ///     name: "*-dev",
        /// });
        /// const admin_token_queries = sdm.getAccount({
        ///     type: "admin-token",
        ///     name: "*-prod",
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_sdm as sdm
        /// 
        /// user_queries = sdm.get_account(type="user",
        ///     email="*@strongdm.com",
        ///     tags={
        ///         "region": "us-west",
        ///         "env": "dev",
        ///     })
        /// api_key_queries = sdm.get_account(type="api",
        ///     name="*-dev")
        /// admin_token_queries = sdm.get_account(type="admin-token",
        ///     name="*-prod")
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = PiersKarsenbarg.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var user_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "user",
        ///         Email = "*@strongdm.com",
        ///         Tags = 
        ///         {
        ///             { "region", "us-west" },
        ///             { "env", "dev" },
        ///         },
        ///     });
        /// 
        ///     var api_key_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "api",
        ///         Name = "*-dev",
        ///     });
        /// 
        ///     var admin_token_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "admin-token",
        ///         Name = "*-prod",
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/pierskarsenbarg/pulumi-sdm/sdk/go/sdm"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type:  pulumi.StringRef("user"),
        /// 			Email: pulumi.StringRef("*@strongdm.com"),
        /// 			Tags: map[string]interface{}{
        /// 				"region": "us-west",
        /// 				"env":    "dev",
        /// 			},
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		_, err = sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type: pulumi.StringRef("api"),
        /// 			Name: pulumi.StringRef("*-dev"),
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		_, err = sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type: pulumi.StringRef("admin-token"),
        /// 			Name: pulumi.StringRef("*-prod"),
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     sdm = {
        ///       source = "pulumi/sdm"
        ///     }
        ///   }
        /// }
        /// 
        /// data "sdm_getaccount" "user-queries" {
        ///   type  = "user"
        ///   email = "*@strongdm.com"
        ///   tags = {
        ///     "region" = "us-west"
        ///     "env"    = "dev"
        ///   }
        /// }
        /// data "sdm_getaccount" "api-key-queries" {
        ///   type = "api"
        ///   name = "*-dev"
        /// }
        /// data "sdm_getaccount" "admin-token-queries" {
        ///   type = "admin-token"
        ///   name = "*-prod"
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.sdm.SdmFunctions;
        /// import com.pulumi.sdm.inputs.GetAccountArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var user-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("user")
        ///             .email("*@strongdm.com")
        ///             .tags(Map.ofEntries(
        ///                 Map.entry("region", "us-west"),
        ///                 Map.entry("env", "dev")
        ///             ))
        ///             .build());
        /// 
        ///         final var api-key-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("api")
        ///             .name("*-dev")
        ///             .build());
        /// 
        ///         final var admin-token-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("admin-token")
        ///             .name("*-prod")
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   user-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: user
        ///         email: '*@strongdm.com'
        ///         tags:
        ///           region: us-west
        ///           env: dev
        ///   api-key-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: api
        ///         name: '*-dev'
        ///   admin-token-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: admin-token
        ///         name: '*-prod'
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetAccountResult> Invoke(GetAccountInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountResult>("sdm:index/getAccount:getAccount", args ?? new GetAccountInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Accounts are users that have access to strongDM. The types of accounts are:
        ///  1. **Users:** humans who are authenticated through username and password or SSO.
        ///  2. **Service Accounts:** machines that are authenticated using a service token.
        ///  3. **Tokens** are access keys with permissions that can be used for authentication.
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as sdm from "@pierskarsenbarg/sdm";
        /// 
        /// const user_queries = sdm.getAccount({
        ///     type: "user",
        ///     email: "*@strongdm.com",
        ///     tags: {
        ///         region: "us-west",
        ///         env: "dev",
        ///     },
        /// });
        /// const api_key_queries = sdm.getAccount({
        ///     type: "api",
        ///     name: "*-dev",
        /// });
        /// const admin_token_queries = sdm.getAccount({
        ///     type: "admin-token",
        ///     name: "*-prod",
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_sdm as sdm
        /// 
        /// user_queries = sdm.get_account(type="user",
        ///     email="*@strongdm.com",
        ///     tags={
        ///         "region": "us-west",
        ///         "env": "dev",
        ///     })
        /// api_key_queries = sdm.get_account(type="api",
        ///     name="*-dev")
        /// admin_token_queries = sdm.get_account(type="admin-token",
        ///     name="*-prod")
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = PiersKarsenbarg.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var user_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "user",
        ///         Email = "*@strongdm.com",
        ///         Tags = 
        ///         {
        ///             { "region", "us-west" },
        ///             { "env", "dev" },
        ///         },
        ///     });
        /// 
        ///     var api_key_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "api",
        ///         Name = "*-dev",
        ///     });
        /// 
        ///     var admin_token_queries = Sdm.GetAccount.Invoke(new()
        ///     {
        ///         Type = "admin-token",
        ///         Name = "*-prod",
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/pierskarsenbarg/pulumi-sdm/sdk/go/sdm"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type:  pulumi.StringRef("user"),
        /// 			Email: pulumi.StringRef("*@strongdm.com"),
        /// 			Tags: map[string]interface{}{
        /// 				"region": "us-west",
        /// 				"env":    "dev",
        /// 			},
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		_, err = sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type: pulumi.StringRef("api"),
        /// 			Name: pulumi.StringRef("*-dev"),
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		_, err = sdm.GetAccount(ctx, &amp;sdm.LookupAccountArgs{
        /// 			Type: pulumi.StringRef("admin-token"),
        /// 			Name: pulumi.StringRef("*-prod"),
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     sdm = {
        ///       source = "pulumi/sdm"
        ///     }
        ///   }
        /// }
        /// 
        /// data "sdm_getaccount" "user-queries" {
        ///   type  = "user"
        ///   email = "*@strongdm.com"
        ///   tags = {
        ///     "region" = "us-west"
        ///     "env"    = "dev"
        ///   }
        /// }
        /// data "sdm_getaccount" "api-key-queries" {
        ///   type = "api"
        ///   name = "*-dev"
        /// }
        /// data "sdm_getaccount" "admin-token-queries" {
        ///   type = "admin-token"
        ///   name = "*-prod"
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.sdm.SdmFunctions;
        /// import com.pulumi.sdm.inputs.GetAccountArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var user-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("user")
        ///             .email("*@strongdm.com")
        ///             .tags(Map.ofEntries(
        ///                 Map.entry("region", "us-west"),
        ///                 Map.entry("env", "dev")
        ///             ))
        ///             .build());
        /// 
        ///         final var api-key-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("api")
        ///             .name("*-dev")
        ///             .build());
        /// 
        ///         final var admin-token-queries = SdmFunctions.getAccount(GetAccountArgs.builder()
        ///             .type("admin-token")
        ///             .name("*-prod")
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   user-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: user
        ///         email: '*@strongdm.com'
        ///         tags:
        ///           region: us-west
        ///           env: dev
        ///   api-key-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: api
        ///         name: '*-dev'
        ///   admin-token-queries:
        ///     fn::invoke:
        ///       function: sdm:getAccount
        ///       arguments:
        ///         type: admin-token
        ///         name: '*-prod'
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetAccountResult> Invoke(GetAccountInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountResult>("sdm:index/getAccount:getAccount", args ?? new GetAccountInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAccountArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Corresponds to the type of token, e.g. api or admin-token.
        /// </summary>
        [Input("accountType")]
        public string? AccountType { get; set; }

        /// <summary>
        /// The User's email address. Must be unique.
        /// </summary>
        [Input("email")]
        public string? Email { get; set; }

        /// <summary>
        /// Internal employee ID used to identify the user.
        /// </summary>
        [Input("employeeNumber")]
        public string? EmployeeNumber { get; set; }

        /// <summary>
        /// External ID is an alternative unique ID this user is represented by within an external service.
        /// </summary>
        [Input("externalId")]
        public string? ExternalId { get; set; }

        /// <summary>
        /// The User's first name.
        /// </summary>
        [Input("firstName")]
        public string? FirstName { get; set; }

        /// <summary>
        /// Unique identifier of the User.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The User's last name.
        /// </summary>
        [Input("lastName")]
        public string? LastName { get; set; }

        /// <summary>
        /// Manager ID is the ID of the user's manager. This field is empty when the user has no manager.
        /// </summary>
        [Input("managerId")]
        public string? ManagerId { get; set; }

        /// <summary>
        /// Unique human-readable name of the Token.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// PermissionLevel is the user's permission level e.g. admin, DBA, user.
        /// </summary>
        [Input("permissionLevel")]
        public string? PermissionLevel { get; set; }

        /// <summary>
        /// Permissions assigned to the token, e.g. role:create.
        /// </summary>
        [Input("permissions")]
        public string? Permissions { get; set; }

        /// <summary>
        /// Reserved for future use.  Always false for tokens.
        /// </summary>
        [Input("suspended")]
        public bool? Suspended { get; set; }

        [Input("tags")]
        private Dictionary<string, string>? _tags;

        /// <summary>
        /// Tags is a map of key, value pairs.
        /// </summary>
        public Dictionary<string, string> Tags
        {
            get => _tags ?? (_tags = new Dictionary<string, string>());
            set => _tags = value;
        }

        /// <summary>
        /// a filter to select all items of a certain subtype. See the [filter documentation](https://docs.strongdm.com/references/cli/filters/) for more information.
        /// </summary>
        [Input("type")]
        public string? Type { get; set; }

        public GetAccountArgs()
        {
        }
        public static new GetAccountArgs Empty => new GetAccountArgs();
    }

    public sealed class GetAccountInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Corresponds to the type of token, e.g. api or admin-token.
        /// </summary>
        [Input("accountType")]
        public Input<string>? AccountType { get; set; }

        /// <summary>
        /// The User's email address. Must be unique.
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// Internal employee ID used to identify the user.
        /// </summary>
        [Input("employeeNumber")]
        public Input<string>? EmployeeNumber { get; set; }

        /// <summary>
        /// External ID is an alternative unique ID this user is represented by within an external service.
        /// </summary>
        [Input("externalId")]
        public Input<string>? ExternalId { get; set; }

        /// <summary>
        /// The User's first name.
        /// </summary>
        [Input("firstName")]
        public Input<string>? FirstName { get; set; }

        /// <summary>
        /// Unique identifier of the User.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The User's last name.
        /// </summary>
        [Input("lastName")]
        public Input<string>? LastName { get; set; }

        /// <summary>
        /// Manager ID is the ID of the user's manager. This field is empty when the user has no manager.
        /// </summary>
        [Input("managerId")]
        public Input<string>? ManagerId { get; set; }

        /// <summary>
        /// Unique human-readable name of the Token.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// PermissionLevel is the user's permission level e.g. admin, DBA, user.
        /// </summary>
        [Input("permissionLevel")]
        public Input<string>? PermissionLevel { get; set; }

        /// <summary>
        /// Permissions assigned to the token, e.g. role:create.
        /// </summary>
        [Input("permissions")]
        public Input<string>? Permissions { get; set; }

        /// <summary>
        /// Reserved for future use.  Always false for tokens.
        /// </summary>
        [Input("suspended")]
        public Input<bool>? Suspended { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Tags is a map of key, value pairs.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// a filter to select all items of a certain subtype. See the [filter documentation](https://docs.strongdm.com/references/cli/filters/) for more information.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetAccountInvokeArgs()
        {
        }
        public static new GetAccountInvokeArgs Empty => new GetAccountInvokeArgs();
    }


    [OutputType]
    public sealed class GetAccountResult
    {
        /// <summary>
        /// Corresponds to the type of token, e.g. api or admin-token.
        /// </summary>
        public readonly string? AccountType;
        /// <summary>
        /// A single element list containing a map, where each key lists one of the following objects:
        /// * service:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAccountAccountResult> Accounts;
        /// <summary>
        /// The User's email address. Must be unique.
        /// </summary>
        public readonly string? Email;
        /// <summary>
        /// Internal employee ID used to identify the user.
        /// </summary>
        public readonly string? EmployeeNumber;
        /// <summary>
        /// External ID is an alternative unique ID this user is represented by within an external service.
        /// </summary>
        public readonly string? ExternalId;
        /// <summary>
        /// The User's first name.
        /// </summary>
        public readonly string? FirstName;
        /// <summary>
        /// Unique identifier of the User.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// a list of strings of ids of data sources that match the given arguments.
        /// </summary>
        public readonly ImmutableArray<string> Ids;
        /// <summary>
        /// The User's last name.
        /// </summary>
        public readonly string? LastName;
        /// <summary>
        /// Manager ID is the ID of the user's manager. This field is empty when the user has no manager.
        /// </summary>
        public readonly string? ManagerId;
        /// <summary>
        /// Unique human-readable name of the Token.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// PermissionLevel is the user's permission level e.g. admin, DBA, user.
        /// </summary>
        public readonly string? PermissionLevel;
        /// <summary>
        /// Permissions assigned to the token, e.g. role:create.
        /// </summary>
        public readonly string? Permissions;
        /// <summary>
        /// Suspended is a read only field for the User's suspended state.
        /// </summary>
        public readonly bool? Suspended;
        /// <summary>
        /// Tags is a map of key, value pairs.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Tags;
        public readonly string? Type;

        [OutputConstructor]
        private GetAccountResult(
            string? accountType,

            ImmutableArray<Outputs.GetAccountAccountResult> accounts,

            string? email,

            string? employeeNumber,

            string? externalId,

            string? firstName,

            string? id,

            ImmutableArray<string> ids,

            string? lastName,

            string? managerId,

            string? name,

            string? permissionLevel,

            string? permissions,

            bool? suspended,

            ImmutableDictionary<string, string>? tags,

            string? type)
        {
            AccountType = accountType;
            Accounts = accounts;
            Email = email;
            EmployeeNumber = employeeNumber;
            ExternalId = externalId;
            FirstName = firstName;
            Id = id;
            Ids = ids;
            LastName = lastName;
            ManagerId = managerId;
            Name = name;
            PermissionLevel = permissionLevel;
            Permissions = permissions;
            Suspended = suspended;
            Tags = tags;
            Type = type;
        }
    }
}
