// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm
{
    public static class GetGroup
    {
        /// <summary>
        /// A Group is a named set of principals.
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var securityTeam = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Name = "Security Team",
        ///     });
        /// 
        ///     var administrators = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Id = "group-1234567890abcdef",
        ///     });
        /// 
        ///     var adminTeams = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Tags = 
        ///         {
        ///             { "admin", "true" },
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetGroupResult> InvokeAsync(GetGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGroupResult>("sdm:index/getGroup:getGroup", args ?? new GetGroupArgs(), options.WithDefaults());

        /// <summary>
        /// A Group is a named set of principals.
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var securityTeam = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Name = "Security Team",
        ///     });
        /// 
        ///     var administrators = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Id = "group-1234567890abcdef",
        ///     });
        /// 
        ///     var adminTeams = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Tags = 
        ///         {
        ///             { "admin", "true" },
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetGroupResult> Invoke(GetGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGroupResult>("sdm:index/getGroup:getGroup", args ?? new GetGroupInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// A Group is a named set of principals.
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var securityTeam = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Name = "Security Team",
        ///     });
        /// 
        ///     var administrators = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Id = "group-1234567890abcdef",
        ///     });
        /// 
        ///     var adminTeams = Sdm.GetGroup.Invoke(new()
        ///     {
        ///         Tags = 
        ///         {
        ///             { "admin", "true" },
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetGroupResult> Invoke(GetGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetGroupResult>("sdm:index/getGroup:getGroup", args ?? new GetGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Description of the Group.
        /// </summary>
        [Input("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Unique identifier of the Group.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Unique human-readable name of the Group.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        [Input("tags")]
        private Dictionary<string, string>? _tags;

        /// <summary>
        /// Tags is a map of key/value pairs that can be attached to a Group.
        /// </summary>
        public Dictionary<string, string> Tags
        {
            get => _tags ?? (_tags = new Dictionary<string, string>());
            set => _tags = value;
        }

        public GetGroupArgs()
        {
        }
        public static new GetGroupArgs Empty => new GetGroupArgs();
    }

    public sealed class GetGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Description of the Group.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Unique identifier of the Group.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Unique human-readable name of the Group.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Tags is a map of key/value pairs that can be attached to a Group.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public GetGroupInvokeArgs()
        {
        }
        public static new GetGroupInvokeArgs Empty => new GetGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetGroupResult
    {
        /// <summary>
        /// Description of the Group.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// A list where each element has the following attributes:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetGroupGroupResult> Groups;
        /// <summary>
        /// Unique identifier of the Group.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// a list of strings of ids of data sources that match the given arguments.
        /// </summary>
        public readonly ImmutableArray<string> Ids;
        /// <summary>
        /// Unique human-readable name of the Group.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Source is a read only field for what service manages this group, e.g. StrongDM, Okta, Azure.
        /// </summary>
        public readonly string Source;
        /// <summary>
        /// Tags is a map of key/value pairs that can be attached to a Group.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Tags;

        [OutputConstructor]
        private GetGroupResult(
            string? description,

            ImmutableArray<Outputs.GetGroupGroupResult> groups,

            string? id,

            ImmutableArray<string> ids,

            string? name,

            string source,

            ImmutableDictionary<string, string>? tags)
        {
            Description = description;
            Groups = groups;
            Id = id;
            Ids = ids;
            Name = name;
            Source = source;
            Tags = tags;
        }
    }
}
