// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm
{
    public static class GetSshCaPubkey
    {
        /// <summary>
        /// The SSH CA Pubkey is a public key used for setting up SSH resources.
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var sshPubkeyQuery = Output.Create(Sdm.GetSshCaPubkey.InvokeAsync());
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetSshCaPubkeyResult> InvokeAsync(GetSshCaPubkeyArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSshCaPubkeyResult>("sdm:index/getSshCaPubkey:getSshCaPubkey", args ?? new GetSshCaPubkeyArgs(), options.WithDefaults());

        /// <summary>
        /// The SSH CA Pubkey is a public key used for setting up SSH resources.
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Sdm = Pulumi.Sdm;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var sshPubkeyQuery = Output.Create(Sdm.GetSshCaPubkey.InvokeAsync());
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetSshCaPubkeyResult> Invoke(GetSshCaPubkeyInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetSshCaPubkeyResult>("sdm:index/getSshCaPubkey:getSshCaPubkey", args ?? new GetSshCaPubkeyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSshCaPubkeyArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// a generated id representing this request.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// the SSH Certificate Authority public key.
        /// </summary>
        [Input("publicKey")]
        public string? PublicKey { get; set; }

        public GetSshCaPubkeyArgs()
        {
        }
    }

    public sealed class GetSshCaPubkeyInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// a generated id representing this request.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// the SSH Certificate Authority public key.
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        public GetSshCaPubkeyInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetSshCaPubkeyResult
    {
        /// <summary>
        /// a generated id representing this request.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// the SSH Certificate Authority public key.
        /// </summary>
        public readonly string? PublicKey;

        [OutputConstructor]
        private GetSshCaPubkeyResult(
            string? id,

            string? publicKey)
        {
            Id = id;
            PublicKey = publicKey;
        }
    }
}
