// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sdm

import (
	"context"
	"reflect"

	"github.com/pierskarsenbarg/pulumi-sdm/sdk/go/sdm/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ApprovalWorkflowStep links an approval workflow step to an ApprovalWorkflow
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pierskarsenbarg/pulumi-sdm/sdk/go/sdm"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sdm.LookupApprovalWorkflowStep(ctx, &sdm.LookupApprovalWorkflowStepArgs{
//				ApprovalFlowId: pulumi.StringRef("af-7935485"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupApprovalWorkflowStep(ctx *pulumi.Context, args *LookupApprovalWorkflowStepArgs, opts ...pulumi.InvokeOption) (*LookupApprovalWorkflowStepResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupApprovalWorkflowStepResult
	err := ctx.Invoke("sdm:index/getApprovalWorkflowStep:getApprovalWorkflowStep", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApprovalWorkflowStep.
type LookupApprovalWorkflowStepArgs struct {
	// The approval flow id specified the approval workfflow that this step belongs to
	ApprovalFlowId *string `pulumi:"approvalFlowId"`
	// Unique identifier of the ApprovalWorkflowStep.
	Id *string `pulumi:"id"`
}

// A collection of values returned by getApprovalWorkflowStep.
type LookupApprovalWorkflowStepResult struct {
	// The approval flow id specified the approval workfflow that this step belongs to
	ApprovalFlowId *string `pulumi:"approvalFlowId"`
	// A list where each element has the following attributes:
	ApprovalWorkflowSteps []GetApprovalWorkflowStepApprovalWorkflowStep `pulumi:"approvalWorkflowSteps"`
	// Unique identifier of the ApprovalWorkflowStep.
	Id *string `pulumi:"id"`
	// a list of strings of ids of data sources that match the given arguments.
	Ids []string `pulumi:"ids"`
}

func LookupApprovalWorkflowStepOutput(ctx *pulumi.Context, args LookupApprovalWorkflowStepOutputArgs, opts ...pulumi.InvokeOption) LookupApprovalWorkflowStepResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupApprovalWorkflowStepResultOutput, error) {
			args := v.(LookupApprovalWorkflowStepArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupApprovalWorkflowStepResult
			secret, err := ctx.InvokePackageRaw("sdm:index/getApprovalWorkflowStep:getApprovalWorkflowStep", args, &rv, "", opts...)
			if err != nil {
				return LookupApprovalWorkflowStepResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupApprovalWorkflowStepResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupApprovalWorkflowStepResultOutput), nil
			}
			return output, nil
		}).(LookupApprovalWorkflowStepResultOutput)
}

// A collection of arguments for invoking getApprovalWorkflowStep.
type LookupApprovalWorkflowStepOutputArgs struct {
	// The approval flow id specified the approval workfflow that this step belongs to
	ApprovalFlowId pulumi.StringPtrInput `pulumi:"approvalFlowId"`
	// Unique identifier of the ApprovalWorkflowStep.
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (LookupApprovalWorkflowStepOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApprovalWorkflowStepArgs)(nil)).Elem()
}

// A collection of values returned by getApprovalWorkflowStep.
type LookupApprovalWorkflowStepResultOutput struct{ *pulumi.OutputState }

func (LookupApprovalWorkflowStepResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApprovalWorkflowStepResult)(nil)).Elem()
}

func (o LookupApprovalWorkflowStepResultOutput) ToLookupApprovalWorkflowStepResultOutput() LookupApprovalWorkflowStepResultOutput {
	return o
}

func (o LookupApprovalWorkflowStepResultOutput) ToLookupApprovalWorkflowStepResultOutputWithContext(ctx context.Context) LookupApprovalWorkflowStepResultOutput {
	return o
}

// The approval flow id specified the approval workfflow that this step belongs to
func (o LookupApprovalWorkflowStepResultOutput) ApprovalFlowId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApprovalWorkflowStepResult) *string { return v.ApprovalFlowId }).(pulumi.StringPtrOutput)
}

// A list where each element has the following attributes:
func (o LookupApprovalWorkflowStepResultOutput) ApprovalWorkflowSteps() GetApprovalWorkflowStepApprovalWorkflowStepArrayOutput {
	return o.ApplyT(func(v LookupApprovalWorkflowStepResult) []GetApprovalWorkflowStepApprovalWorkflowStep {
		return v.ApprovalWorkflowSteps
	}).(GetApprovalWorkflowStepApprovalWorkflowStepArrayOutput)
}

// Unique identifier of the ApprovalWorkflowStep.
func (o LookupApprovalWorkflowStepResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApprovalWorkflowStepResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// a list of strings of ids of data sources that match the given arguments.
func (o LookupApprovalWorkflowStepResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApprovalWorkflowStepResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApprovalWorkflowStepResultOutput{})
}
