// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Outputs
{

    [OutputType]
    public sealed class ConnectorGcp
    {
        /// <summary>
        /// Description of the Connector.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// ExcludeTags filters out discovered resources that have the tag and value. We do allow duplicate tag names for ExcludeTags to support multiple excluded values for the tag.
        /// </summary>
        public readonly ImmutableArray<Outputs.ConnectorGcpExcludeTag> ExcludeTags;
        /// <summary>
        /// IncludeTags only discovers cloud resources that have one of the included tags. We do not allow duplicate tag names for IncludeTags
        /// </summary>
        public readonly ImmutableArray<Outputs.ConnectorGcpIncludeTag> IncludeTags;
        /// <summary>
        /// Unique human-readable name of the Connector.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// ProjectIds is the list of GCP Projects the connector will scan
        /// </summary>
        public readonly ImmutableArray<string> ProjectIds;
        /// <summary>
        /// ScanPeriod identifies which remote system this Connector discovers
        /// </summary>
        public readonly string? ScanPeriod;
        /// <summary>
        /// Services is a list of services this connector should scan.
        /// </summary>
        public readonly ImmutableArray<string> Services;
        /// <summary>
        /// WorkloadPoolId is the GCP Workload Pool Identifier used to authenticate our JWT
        /// </summary>
        public readonly string? WorkloadPoolId;
        /// <summary>
        /// WorkloadProjectId is the GCP Project ID where the Workload Pool is defined
        /// </summary>
        public readonly string? WorkloadProjectId;
        /// <summary>
        /// WorkloadProjectNumber is the GCP Project Number where the Workload Pool is defined
        /// </summary>
        public readonly string? WorkloadProjectNumber;
        /// <summary>
        /// WorkloadProviderId is the GCP Workload Provider Identifier used to authenticate our JWT
        /// </summary>
        public readonly string? WorkloadProviderId;

        [OutputConstructor]
        private ConnectorGcp(
            string? description,

            ImmutableArray<Outputs.ConnectorGcpExcludeTag> excludeTags,

            ImmutableArray<Outputs.ConnectorGcpIncludeTag> includeTags,

            string name,

            ImmutableArray<string> projectIds,

            string? scanPeriod,

            ImmutableArray<string> services,

            string? workloadPoolId,

            string? workloadProjectId,

            string? workloadProjectNumber,

            string? workloadProviderId)
        {
            Description = description;
            ExcludeTags = excludeTags;
            IncludeTags = includeTags;
            Name = name;
            ProjectIds = projectIds;
            ScanPeriod = scanPeriod;
            Services = services;
            WorkloadPoolId = workloadPoolId;
            WorkloadProjectId = workloadProjectId;
            WorkloadProjectNumber = workloadProjectNumber;
            WorkloadProviderId = workloadProviderId;
        }
    }
}
