// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Outputs
{

    [OutputType]
    public sealed class GetApprovalWorkflowApprovalStepApproverResult
    {
        /// <summary>
        /// The account id of the approver (only one of account_id, role_id, group id, or reference may be present for one approver)
        /// </summary>
        public readonly string? AccountId;
        /// <summary>
        /// The group id of the approver (only one of account_id, role_id, group id, or reference may be present for one approver)
        /// </summary>
        public readonly string? GroupId;
        /// <summary>
        /// A reference to an approver: 'manager-of-requester' or 'manager-of-manager-of-requester' (only one of account_id, role_id, group id, or reference may be present for one approver)
        /// </summary>
        public readonly string? Reference;
        /// <summary>
        /// The role id of the approver (only one of account_id, role_id, group id, or reference may be present for one approver)
        /// </summary>
        public readonly string? RoleId;

        [OutputConstructor]
        private GetApprovalWorkflowApprovalStepApproverResult(
            string? accountId,

            string? groupId,

            string? reference,

            string? roleId)
        {
            AccountId = accountId;
            GroupId = groupId;
            Reference = reference;
            RoleId = roleId;
        }
    }
}
