// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Outputs
{

    [OutputType]
    public sealed class GetConnectorDiscoveryConnectorAzureResult
    {
        /// <summary>
        /// ClientId is the ID of the Application / Service Account we're acting as
        /// </summary>
        public readonly string? ClientId;
        /// <summary>
        /// Description of the Connector.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Unique identifier of the Connector.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Unique human-readable name of the Connector.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// ScanPeriod identifies which remote system this Connector discovers
        /// </summary>
        public readonly string? ScanPeriod;
        /// <summary>
        /// Services is a list of services this connector should scan.
        /// </summary>
        public readonly ImmutableArray<string> Services;
        /// <summary>
        /// SubscriptionIds are the targets of discovery.
        /// </summary>
        public readonly ImmutableArray<string> SubscriptionIds;
        /// <summary>
        /// TenantId is the Azure Tenant we're discovering in
        /// </summary>
        public readonly string? TenantId;

        [OutputConstructor]
        private GetConnectorDiscoveryConnectorAzureResult(
            string? clientId,

            string? description,

            string? id,

            string? name,

            string? scanPeriod,

            ImmutableArray<string> services,

            ImmutableArray<string> subscriptionIds,

            string? tenantId)
        {
            ClientId = clientId;
            Description = description;
            Id = id;
            Name = name;
            ScanPeriod = scanPeriod;
            Services = services;
            SubscriptionIds = subscriptionIds;
            TenantId = tenantId;
        }
    }
}
