// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Outputs
{

    [OutputType]
    public sealed class GetPeeringGroupResourcePeeringGroupResourceResult
    {
        /// <summary>
        /// Peering Group ID to which the resource will be attached to.
        /// </summary>
        public readonly string? GroupId;
        /// <summary>
        /// Unique identifier of the Attachment.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Resource ID to be attached.
        /// </summary>
        public readonly string? ResourceId;

        [OutputConstructor]
        private GetPeeringGroupResourcePeeringGroupResourceResult(
            string? groupId,

            string? id,

            string? resourceId)
        {
            GroupId = groupId;
            Id = id;
            ResourceId = resourceId;
        }
    }
}
