// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Outputs
{

    [OutputType]
    public sealed class GetResourceResourceMongoShardedClusterResult
    {
        public readonly string? AuthDatabase;
        /// <summary>
        /// Bind interface
        /// </summary>
        public readonly string? BindInterface;
        /// <summary>
        /// A filter applied to the routing logic to pin datasource to nodes.
        /// </summary>
        public readonly string? EgressFilter;
        public readonly string? Hostname;
        /// <summary>
        /// Unique identifier of the Resource.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Unique human-readable name of the Resource.
        /// </summary>
        public readonly string? Name;
        public readonly string? Password;
        public readonly int PortOverride;
        /// <summary>
        /// ID of the secret store containing credentials for this resource, if any.
        /// </summary>
        public readonly string? SecretStoreId;
        /// <summary>
        /// Tags is a map of key, value pairs.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Tags;
        public readonly bool? TlsRequired;
        public readonly string? Username;

        [OutputConstructor]
        private GetResourceResourceMongoShardedClusterResult(
            string? authDatabase,

            string? bindInterface,

            string? egressFilter,

            string? hostname,

            string? id,

            string? name,

            string? password,

            int portOverride,

            string? secretStoreId,

            ImmutableDictionary<string, string>? tags,

            bool? tlsRequired,

            string? username)
        {
            AuthDatabase = authDatabase;
            BindInterface = bindInterface;
            EgressFilter = egressFilter;
            Hostname = hostname;
            Id = id;
            Name = name;
            Password = password;
            PortOverride = portOverride;
            SecretStoreId = secretStoreId;
            Tags = tags;
            TlsRequired = tlsRequired;
            Username = username;
        }
    }
}
