// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Outputs
{

    [OutputType]
    public sealed class GetSecretStoreSecretStoreGcpCertX509StoreResult
    {
        /// <summary>
        /// The ID of the target CA
        /// </summary>
        public readonly string? CaId;
        /// <summary>
        /// The ID of the target CA pool
        /// </summary>
        public readonly string? CaPoolId;
        /// <summary>
        /// Unique identifier of the SecretStore.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The lifetime of certificates issued by this CA represented in minutes.
        /// </summary>
        public readonly int? IssuedCertTtlMinutes;
        /// <summary>
        /// The Region for the CA in GCP format e.g. us-west1
        /// </summary>
        public readonly string? Location;
        /// <summary>
        /// Unique human-readable name of the SecretStore.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The GCP project ID to target.
        /// </summary>
        public readonly string? ProjectId;
        /// <summary>
        /// Tags is a map of key, value pairs.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Tags;

        [OutputConstructor]
        private GetSecretStoreSecretStoreGcpCertX509StoreResult(
            string? caId,

            string? caPoolId,

            string? id,

            int? issuedCertTtlMinutes,

            string? location,

            string? name,

            string? projectId,

            ImmutableDictionary<string, string>? tags)
        {
            CaId = caId;
            CaPoolId = caPoolId;
            Id = id;
            IssuedCertTtlMinutes = issuedCertTtlMinutes;
            Location = location;
            Name = name;
            ProjectId = projectId;
            Tags = tags;
        }
    }
}
