// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Outputs
{

    [OutputType]
    public sealed class GetSecretStoreSecretStoreResult
    {
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreAwResult> Aws;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreAzureStoreResult> AzureStores;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreCyberarkConjurResult> CyberarkConjurs;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreCyberarkPamExperimentalResult> CyberarkPamExperimentals;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreCyberarkPamResult> CyberarkPams;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreDelineaStoreResult> DelineaStores;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreGcpStoreResult> GcpStores;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreVaultApproleResult> VaultApproles;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreVaultTlResult> VaultTls;
        public readonly ImmutableArray<Outputs.GetSecretStoreSecretStoreVaultTokenResult> VaultTokens;

        [OutputConstructor]
        private GetSecretStoreSecretStoreResult(
            ImmutableArray<Outputs.GetSecretStoreSecretStoreAwResult> aws,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreAzureStoreResult> azureStores,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreCyberarkConjurResult> cyberarkConjurs,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreCyberarkPamExperimentalResult> cyberarkPamExperimentals,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreCyberarkPamResult> cyberarkPams,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreDelineaStoreResult> delineaStores,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreGcpStoreResult> gcpStores,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreVaultApproleResult> vaultApproles,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreVaultTlResult> vaultTls,

            ImmutableArray<Outputs.GetSecretStoreSecretStoreVaultTokenResult> vaultTokens)
        {
            Aws = aws;
            AzureStores = azureStores;
            CyberarkConjurs = cyberarkConjurs;
            CyberarkPamExperimentals = cyberarkPamExperimentals;
            CyberarkPams = cyberarkPams;
            DelineaStores = delineaStores;
            GcpStores = gcpStores;
            VaultApproles = vaultApproles;
            VaultTls = vaultTls;
            VaultTokens = vaultTokens;
        }
    }
}
