# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetOrgUrlInfoResult',
    'AwaitableGetOrgUrlInfoResult',
    'get_org_url_info',
    'get_org_url_info_output',
]

@pulumi.output_type
class GetOrgUrlInfoResult:
    """
    A collection of values returned by getOrgUrlInfo.
    """
    def __init__(__self__, base_url=None, id=None, oidc_issuer_url=None, saml_metadata_url=None, websites_subdomain=None):
        if base_url and not isinstance(base_url, str):
            raise TypeError("Expected argument 'base_url' to be a str")
        pulumi.set(__self__, "base_url", base_url)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if oidc_issuer_url and not isinstance(oidc_issuer_url, str):
            raise TypeError("Expected argument 'oidc_issuer_url' to be a str")
        pulumi.set(__self__, "oidc_issuer_url", oidc_issuer_url)
        if saml_metadata_url and not isinstance(saml_metadata_url, str):
            raise TypeError("Expected argument 'saml_metadata_url' to be a str")
        pulumi.set(__self__, "saml_metadata_url", saml_metadata_url)
        if websites_subdomain and not isinstance(websites_subdomain, str):
            raise TypeError("Expected argument 'websites_subdomain' to be a str")
        pulumi.set(__self__, "websites_subdomain", websites_subdomain)

    @_builtins.property
    @pulumi.getter(name="baseUrl")
    def base_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "base_url")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="oidcIssuerUrl")
    def oidc_issuer_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "oidc_issuer_url")

    @_builtins.property
    @pulumi.getter(name="samlMetadataUrl")
    def saml_metadata_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "saml_metadata_url")

    @_builtins.property
    @pulumi.getter(name="websitesSubdomain")
    def websites_subdomain(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "websites_subdomain")


class AwaitableGetOrgUrlInfoResult(GetOrgUrlInfoResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOrgUrlInfoResult(
            base_url=self.base_url,
            id=self.id,
            oidc_issuer_url=self.oidc_issuer_url,
            saml_metadata_url=self.saml_metadata_url,
            websites_subdomain=self.websites_subdomain)


def get_org_url_info(base_url: Optional[_builtins.str] = None,
                     id: Optional[_builtins.str] = None,
                     oidc_issuer_url: Optional[_builtins.str] = None,
                     saml_metadata_url: Optional[_builtins.str] = None,
                     websites_subdomain: Optional[_builtins.str] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOrgUrlInfoResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['baseUrl'] = base_url
    __args__['id'] = id
    __args__['oidcIssuerUrl'] = oidc_issuer_url
    __args__['samlMetadataUrl'] = saml_metadata_url
    __args__['websitesSubdomain'] = websites_subdomain
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('sdm:index/getOrgUrlInfo:getOrgUrlInfo', __args__, opts=opts, typ=GetOrgUrlInfoResult).value

    return AwaitableGetOrgUrlInfoResult(
        base_url=pulumi.get(__ret__, 'base_url'),
        id=pulumi.get(__ret__, 'id'),
        oidc_issuer_url=pulumi.get(__ret__, 'oidc_issuer_url'),
        saml_metadata_url=pulumi.get(__ret__, 'saml_metadata_url'),
        websites_subdomain=pulumi.get(__ret__, 'websites_subdomain'))
def get_org_url_info_output(base_url: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            oidc_issuer_url: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            saml_metadata_url: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            websites_subdomain: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetOrgUrlInfoResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['baseUrl'] = base_url
    __args__['id'] = id
    __args__['oidcIssuerUrl'] = oidc_issuer_url
    __args__['samlMetadataUrl'] = saml_metadata_url
    __args__['websitesSubdomain'] = websites_subdomain
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('sdm:index/getOrgUrlInfo:getOrgUrlInfo', __args__, opts=opts, typ=GetOrgUrlInfoResult)
    return __ret__.apply(lambda __response__: GetOrgUrlInfoResult(
        base_url=pulumi.get(__response__, 'base_url'),
        id=pulumi.get(__response__, 'id'),
        oidc_issuer_url=pulumi.get(__response__, 'oidc_issuer_url'),
        saml_metadata_url=pulumi.get(__response__, 'saml_metadata_url'),
        websites_subdomain=pulumi.get(__response__, 'websites_subdomain')))
