// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Sdm.Inputs
{

    public sealed class SecretEnginePostgresSecretEngineArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The default time-to-live duration of the password after it's read. Once the ttl has passed, a password will be rotated.
        /// </summary>
        [Input("afterReadTtl")]
        public Input<string>? AfterReadTtl { get; set; }

        /// <summary>
        /// Database is the database to verify credential against.
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        /// <summary>
        /// Hostname is the hostname or IP address of the Postgres server.
        /// </summary>
        [Input("hostname", required: true)]
        public Input<string> Hostname { get; set; } = null!;

        /// <summary>
        /// An interval of public/private key rotation for secret engine in days
        /// </summary>
        [Input("keyRotationIntervalDays")]
        public Input<int>? KeyRotationIntervalDays { get; set; }

        /// <summary>
        /// Unique human-readable name of the Secret Engine.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Password is the password to connect to the Postgres server.
        /// </summary>
        [Input("password", required: true)]
        public Input<string> Password { get; set; } = null!;

        /// <summary>
        /// Port is the port number of the Postgres server.
        /// </summary>
        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        /// <summary>
        /// Public key linked with a secret engine
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        /// <summary>
        /// Backing secret store identifier
        /// </summary>
        [Input("secretStoreId", required: true)]
        public Input<string> SecretStoreId { get; set; } = null!;

        /// <summary>
        /// Backing Secret Store root path where managed secrets are going to be stored
        /// </summary>
        [Input("secretStoreRootPath", required: true)]
        public Input<string> SecretStoreRootPath { get; set; } = null!;

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Tags is a map of key, value pairs.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// TLS enables TLS/SSL when connecting to the Postgres server.
        /// </summary>
        [Input("tls")]
        public Input<bool>? Tls { get; set; }

        /// <summary>
        /// The default password time-to-live duration. Once the ttl has passed, a password will be rotated the next time it's requested.
        /// </summary>
        [Input("ttl")]
        public Input<string>? Ttl { get; set; }

        /// <summary>
        /// Username is the username to connect to the Postgres server.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public SecretEnginePostgresSecretEngineArgs()
        {
        }
        public static new SecretEnginePostgresSecretEngineArgs Empty => new SecretEnginePostgresSecretEngineArgs();
    }
}
