// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A GroupRole assigns a Group to a Role.
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdm from "@pierskarsenbarg/sdm";
 *
 * const securityTeamToProductionAccess = new sdm.GroupRole("securityTeamToProductionAccess", {
 *     groupId: sdm_group.security_team.id,
 *     roleId: sdm_role.production_access.id,
 * });
 * const administratorsToAdminAccess = new sdm.GroupRole("administratorsToAdminAccess", {
 *     groupId: "group-1234567890abcdef",
 *     roleId: "r-1234567890abcdef",
 * });
 * ```
 * This resource can be imported using the import command.
 *
 * ## Import
 *
 * A GroupRole can be imported using the id, e.g.,
 *
 * ```sh
 * $ pulumi import sdm:index/groupRole:GroupRole example grouprole-12345678
 * ```
 */
export class GroupRole extends pulumi.CustomResource {
    /**
     * Get an existing GroupRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupRoleState, opts?: pulumi.CustomResourceOptions): GroupRole {
        return new GroupRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sdm:index/groupRole:GroupRole';

    /**
     * Returns true if the given object is an instance of GroupRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GroupRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GroupRole.__pulumiType;
    }

    /**
     * The assigned Group ID.
     */
    declare public readonly groupId: pulumi.Output<string>;
    /**
     * The assigned Role ID.
     */
    declare public readonly roleId: pulumi.Output<string>;

    /**
     * Create a GroupRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupRoleArgs | GroupRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupRoleState | undefined;
            resourceInputs["groupId"] = state?.groupId;
            resourceInputs["roleId"] = state?.roleId;
        } else {
            const args = argsOrState as GroupRoleArgs | undefined;
            if (args?.groupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'groupId'");
            }
            if (args?.roleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            resourceInputs["groupId"] = args?.groupId;
            resourceInputs["roleId"] = args?.roleId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GroupRole.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GroupRole resources.
 */
export interface GroupRoleState {
    /**
     * The assigned Group ID.
     */
    groupId?: pulumi.Input<string>;
    /**
     * The assigned Role ID.
     */
    roleId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GroupRole resource.
 */
export interface GroupRoleArgs {
    /**
     * The assigned Group ID.
     */
    groupId: pulumi.Input<string>;
    /**
     * The assigned Role ID.
     */
    roleId: pulumi.Input<string>;
}
